name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-node:
    runs-on: ubuntu-latest
    name: Build & Test Node.js
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
        if: exists('package.json')
      - name: Run tests
        run: npm test
        if: exists('package.json')

  build-python:
    runs-on: ubuntu-latest
    name: Build & Test Python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          if [ -f pytest.ini ] || [ -f tests/ ]; then pytest; fi
